"""empty message

Revision ID: 6550cfe35a13
Revises: 
Create Date: 2023-03-14 18:51:18.424455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6550cfe35a13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reg_code', sa.String(length=10), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reg_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reg_code', sa.VARCHAR(length=10), nullable=False))

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('reg_code')

    # ### end Alembic commands ###
